Added the ability to toggle between light and dark themes.
chamerling/gitlab-teams pull request #60
Opened 2019-10-04 04:18 UTC by cdterry87

2019-10-04 04:19 UTC, cdterry87 commented
This should take care of Issue #56

2019-10-04 08:17 UTC, chamerling commented
There are components which are still dark

![Capture d’écran 2019-10-04 à 10 15 38](https://user-images.githubusercontent.com/264403/66192097-0da35d80-e690-11e9-8225-fec5e0df97dd.png)
![Capture d’écran 2019-10-04 à 10 15 17](https://user-images.githubusercontent.com/264403/66192098-0da35d80-e690-11e9-92e6-424ba969fba6.png)
![Capture d’écran 2019-10-04 à 10 15 12](https://user-images.githubusercontent.com/264403/66192099-0da35d80-e690-11e9-908a-53a00db295ab.png)
![Capture d’écran 2019-10-04 à 10 15 07](https://user-images.githubusercontent.com/264403/66192100-0da35d80-e690-11e9-86ce-2981a17a0756.png)
![Capture d’écran 2019-10-04 à 10 14 58](https://user-images.githubusercontent.com/264403/66192101-0e3bf400-e690-11e9-9e7a-a34b76291fe2.png)

2019-10-04 13:15 UTC, cdterry87 commented
@chamerling Thank you for letting me know.  I'll try working on getting these components today to make them reflect the specified theme, as well.

2019-10-04 13:51 UTC, cdterry87 commented
@chamerling I have made the requested changes.  Please let me know if there are any additional issues.

2019-10-04 16:58 UTC, chamerling commented
@cdterry87 nice. Looks like there is on issue when selecting a team

![Capture d’écran 2019-10-04 à 18 56 38](https://user-images.githubusercontent.com/264403/66225505-e1f89580-e6d8-11e9-9daf-f2e60e8120fb.png)

2019-10-04 17:05 UTC, cdterry87 commented
I must have overlooked that one.  I just submitted another commit to fix it.  Check it out now, and let me know if it is better now.

2019-10-04 17:09 UTC, chamerling commented
This is great now :) Thx a lot!

2019-10-04 17:10 UTC, chamerling approved these changes

2019-10-04 17:10 UTC, chamerling commented on src/store/modules/settings.js
> +  darkMode: localStorage.getItem("darkMode"),
Maybe you can transform the localstorage in boolean directly in the state?

2019-10-04 17:10 UTC, chamerling commented on src/App.vue
> +      return (typeof this.$store.state.settings.darkMode != "boolean" ? true : this.$store.state.settings.darkMode);
What about? 

```suggestion
  return !!this.$store.state.settings.darkMode;
```

2019-10-04 17:10 UTC, chamerling commented on src/views/Settings.vue
> +    this.localDarkMode = (this.$store.state.settings.darkMode == "false" ? false : true);
Use boolean directly from the state

2019-10-04 17:10 UTC, chamerling commented on src/views/Settings.vue
> +        this.localDarkMode = value;
You can avoid watching and dispatch directly in the setter

```suggestion
        this.$store.dispatch("updateTheme", value);
```

2019-10-04 17:10 UTC, chamerling commented on src/store/modules/settings.js
> +  darkMode: localStorage.getItem("darkMode"),
Can you address this one? Having the watcher is useless then

2019-10-04 17:12 UTC, chamerling commented on src/views/Settings.vue
> +      this.$store.dispatch("updateTheme", toggle);
Remove this useless watcher and dispatch in the setter has described above, WDYT?

2019-10-04 17:13 UTC, chamerling requested changes
Please remove the watcher, use the setter to dispatch the action instead

2019-10-04 19:41 UTC, cdterry87 commented
> Please remove the watcher, use the setter to dispatch the action instead

I attempted to resolve this a few different ways without the watcher, but using the watcher was the only way I could get it to work.  Any ideas? Could you point me in the right direction?

2019-10-07 07:15 UTC, chamerling commented on src/views/Settings.vue
> +                  v-model="localDarkMode"
bind to `darkMode` and remove ALL the `localDarkMode`declaration and references. The `darkMode` getter and setter should do the trick

2019-10-07 07:16 UTC, chamerling commented
> > Please remove the watcher, use the setter to dispatch the action instead
> 
> I attempted to resolve this a few different ways without the watcher, but using the watcher was the only way I could get it to work. Any ideas? Could you point me in the right direction?

Check this https://github.com/chamerling/gitlab-teams/pull/60#discussion_r331870457

2019-10-08 00:42 UTC, cdterry87 commented
@chamerling lol, I was so close!  I have implemented your suggested changes.  Once again, I appreciate your help.  Let me know if there is anything else that needs to be done.

2019-10-08 07:27 UTC, chamerling commented on src/views/Settings.vue
> +    this.darkMode = this.$store.state.settings.darkMode;
This line is useless if you have the computed property

2019-10-08 07:27 UTC, chamerling commented on src/views/Settings.vue
> +      this.$store.dispatch("updateTheme", toggle);
Remove the watcher since you have the computed property

2019-10-08 07:28 UTC, chamerling commented
@cdterry87 you are close to the perfection, I commented what you need to remove

2019-10-08 13:01 UTC, cdterry87 commented
@chamerling Sorry about that! The unnecessary lines have been removed.

2019-10-08 13:24 UTC, merged